name: build_get5_eventula_apistats

on:
  push:
    branches: [ master ]
    tags: [ v**]
    paths:
      - '**'
      - '!README.md'
      - '!LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: get get5_eventula_apistats
      - name: Build Docker build container
        run: docker build get5_eventula_apistats -t get5eventulaapistatsbuild:latest
      - name: Build get5_eventula_apistats
        shell: bash
        run: docker run --rm -v $PWD:/get5src -v $PWD/build/output:/get5/builds get5eventulaapistatsbuild:latest
      - name: list build
        shell: bash
        working-directory: ./build/output
        run: ls
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./build/output/get5_eventula_apistats-*.zip
          retention-days: 1

  release:
    name: Release
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: get artifacts
      uses: actions/download-artifact@v2
    - name: Display structure of downloaded files
      run: ls -R
    - name: Release
      if: ${{ !(contains(github.ref, '-beta')) }}
      uses: softprops/action-gh-release@v1
      with:
        files: ./artifact/get5_eventula_apistats-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
    - name: pre Release
      if: ${{ (contains(github.ref, '-beta')) }}
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: ./artifact/get5_eventula_apistats-*.zip 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}